name: "Test"
on: [push, pull_request] 

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      
    - uses: pnpm/action-setup@v6
      with:
        version: 11.7.0

    - uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'pnpm'

    - name: "pnpm install"
      run: pnpm install

    - name: "pnpm test"
      run: pnpm test